tilt_joints_position_controller:
  type: position_controllers/JointGroupPositionController
  joints:
    - red/tilt_joint_0
    - red/tilt_joint_1
    - red/tilt_joint_2
    - red/tilt_joint_3

manipulator_COM_position_controller:
  type: position_controllers/JointPositionController
  joint: red/movable_mass_joint_0

movable_mass_joints_velocity_controller:
  type: velocity_controllers/JointGroupVelocityController
  joints:
    - red/movable_mass_joint_1
    - red/movable_mass_joint_2
    - red/movable_mass_joint_3
    - red/movable_mass_joint_4
