joint_position_controller:
  type: position_controllers/JointGroupPositionController
  joints:
    - red/tilt_joint_0
    - red/tilt_joint_1
    - red/tilt_joint_2
    - red/tilt_joint_3
    - red/movable_mass_joint_0