<?xml version="1.0"?>

<robot xmlns:xacro="http://ros.org/wiki/xacro">
  



  <!-- Macro for propeler tilting joint and link.-->

  <xacro:macro name="prop_tilt" 
    params="robot_namespace parent number x_axis y_axis mass length radius *origin">

    <joint name="${robot_namespace}/tilt_joint_${number}" type="revolute">
      <xacro:insert_block name="origin"/>
      <parent link="${parent}"/>
      <child link="${robot_namespace}/tilt_link_${number}"/>
      <axis xyz="${x_axis} ${y_axis} 0"/>
      <limit lower="-0.785398163" upper="0.785398163" effort="100000" velocity="3"/>
    </joint>
    
    <link name="${robot_namespace}/tilt_link_${number}">
      <visual>
        <origin rpy="0 0 0" xyz="0 0 ${length/2}"/>
        <geometry>
          <cylinder length="${length}" radius="${radius}" />
        </geometry>
      </visual>
      
      <inertial>
        <origin rpy="0 0 0" xyz="0 0 ${length/2}"/>
        <mass value="${mass}" />
        <inertia
            ixx="${1/12 * mass * (3.0 * radius * radius + length * length)}"      ixy="0.0"                                                             ixz="0.0"
            iyx="0.0"                                                             iyy="${1/12 * mass * (3.0 * radius * radius + length * length)}"      iyz="0.0"
            izx="0.0"                                                             izy="0.0"                                                             izz="${1/2 * mass * radius * radius}" />
      </inertial>
    </link>
  </xacro:macro>



  <!-- Macro for movable mass on a straight line. -->
  
  <xacro:macro name="movable_mass_linear" 
    params="robot_namespace number parent mass radius path_len color x_axis y_axis z_axis *origin">

    <joint name="${robot_namespace}/movable_mass_joint_${number}" type="prismatic">
      <xacro:insert_block name="origin"/>
      <axis xyz="${x_axis} ${y_axis} ${z_axis}"/>
      <parent link="${parent}"/>
      <child link="${robot_namespace}/movable_mass_link_${number}"/>
      <limit lower="${-path_len/2}" upper="${path_len/2}" effort="10000" velocity="20"/>
    </joint>

    <link name="${robot_namespace}/movable_mass_link_${number}">
      <visual>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry>
          <sphere radius="${radius}"/>
        </geometry>
      </visual>
      
      <inertial>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <mass value="${mass}"/>
        <inertia
            ixx="${2/5 * mass * radius * radius}"     ixy="0.0"                                  ixz="0.0"
            iyx="0.0"                                 iyy="${2/5 * mass * radius * radius}"      iyz="0.0"
            izx="0.0"                                 izy="0.0"                                  izz="${2/5 * mass * radius * radius}" />
      </inertial>
    </link>

    <gazebo reference="${robot_namespace}/movable_mass_link_${number}">
      <material>Gazebo/${color}</material>
    </gazebo>
  </xacro:macro>





  <!-- We add a <transmission> block for every joint that we wish to actuate. -->

  <xacro:macro name="tilt_joint_transmission" params="number joint_name">
    <transmission name="tilt_joint_transmission_${number}">
      <type>transmission_interface/SimpleTransmission</type>
      <actuator name="tilt_joint_motor_${number}">
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
      <joint name="${joint_name}">
        <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      </joint>
    </transmission>
  </xacro:macro>

  <xacro:macro name="movable_mass_transmission" params="number joint_name">
    <transmission name="movable_mass_transmission_${number}">
      <type>transmission_interface/SimpleTransmission</type>
      <actuator name="movable_mass_motor_${number}">
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
      <joint name="${joint_name}">
        <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      </joint>
    </transmission>
  </xacro:macro>

  


</robot>